@echo off
setlocal enabledelayedexpansion

REM Get the IPv4 address from the active WiFi or Ethernet adapter with a default gateway
for /f "tokens=2 delims=:" %%a in ('ipconfig ^| findstr /c:"Default Gateway"') do (
    set gateway=%%a
    set gateway=!gateway: =!
    if not "!gateway!"=="" (
        REM Found an adapter with a gateway, now get its IP
        for /f "tokens=2 delims=:" %%b in ('ipconfig ^| findstr /c:"IPv4 Address"') do (
            set ip=%%b
            set ip=!ip: =!
            REM Skip VirtualBox/VMware IPs (192.168.56.x, 192.168.99.x)
            echo !ip! | findstr /r "^192\.168\.56\." >nul
            if errorlevel 1 (
                echo !ip! | findstr /r "^192\.168\.99\." >nul
                if errorlevel 1 (
                    goto :found
                )
            )
        )
    )
)

:found
if not defined ip (
    echo Error: Could not find IPv4 address with internet access
    echo Please manually update .env file
    exit /b 1
)

echo Detected IP Address: !ip!

REM Update the .env file
echo # API Configuration> .env
echo # Auto-generated by update-ip.bat>> .env
echo VITE_API_BASE_URL=http://!ip!:8080/api>> .env

echo .env file updated with IP: !ip!
