@echo off
setlocal enabledelayedexpansion

echo ======================================
echo Cloudflare Tunnel Configuration
echo ======================================
echo.
echo Este script vai configurar as URLs do Cloudflare Tunnel
echo.

REM Prompt for backend URL
echo Por favor, insira a URL do Cloudflare Tunnel para o BACKEND
echo Exemplo: https://abc-123-def.trycloudflare.com
echo (Sem barra no final)
echo.
set /p BACKEND_URL="Backend URL: "

REM Validate backend URL
if "!BACKEND_URL!"=="" (
    echo Erro: URL do backend nao pode estar vazia
    pause
    exit /b 1
)

echo.
echo Por favor, insira a URL do Cloudflare Tunnel para o FRONTEND
echo Exemplo: https://xyz-456-uvw.trycloudflare.com
echo (Sem barra no final)
echo.
set /p FRONTEND_URL="Frontend URL: "

REM Validate frontend URL
if "!FRONTEND_URL!"=="" (
    echo Erro: URL do frontend nao pode estar vazia
    pause
    exit /b 1
)

echo.
echo ======================================
echo Atualizando arquivos .env...
echo ======================================
echo.

REM Update frontend .env
echo # Backend API URL - Cloudflare Tunnel> frontend\.env
echo # Auto-generated by update-cloudflare-env.bat>> frontend\.env
echo # Last updated: %date% %time%>> frontend\.env
echo VITE_API_BASE_URL=!BACKEND_URL!/api>> frontend\.env

echo [OK] Frontend .env atualizado
echo      VITE_API_BASE_URL=!BACKEND_URL!/api
echo.

REM Update backend .env (or application.properties override)
echo # Frontend URL - Cloudflare Tunnel> backend\.env
echo # Auto-generated by update-cloudflare-env.bat>> backend\.env
echo # Last updated: %date% %time%>> backend\.env
echo FRONTEND_URL=!FRONTEND_URL!>> backend\.env

echo [OK] Backend .env atualizado
echo      FRONTEND_URL=!FRONTEND_URL!
echo.

echo ======================================
echo Configuracao concluida com sucesso!
echo ======================================
echo.
echo URLs configuradas:
echo   Frontend: !FRONTEND_URL!
echo   Backend:  !BACKEND_URL!
echo.
echo Proximo passo:
echo   1. Certifique-se de que os tuneis Cloudflare estao rodando
echo   2. Inicie o backend: cd backend ^&^& mvnw spring-boot:run
echo   3. Inicie o frontend: cd frontend ^&^& npm run dev:localhost
echo.
pause
